import test from "node:test";
import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
test("website includes canonical Pipo MenuWeb bundle", async () => {
  const appRoot = resolve(root, "..");
  for (const file of ["index.html", "menu.css", "menu.js", "menu-helpers.js", "demo-fixture.json", "pipoclick.mp3", "css/fontawesome.min.css"]) {
    await assert.doesNotReject(access(resolve(root, "public/pipo-menu", file)));
  }
  const html = await readFile(resolve(root, "public/pipo-menu/index.html"), "utf8");
  assert.match(html, /menu\.js/);
  assert.match(html, /menu-helpers\.js/);
  assert.doesNotMatch(html, /https:\/\//);
  const hash = createHash("sha256");
  for (const file of ["index.html", "menu.css", "menu.js", "menu-helpers.js", "demo-fixture.json", "pipoclick.mp3", "css/fontawesome.min.css", "webfonts/fa-regular-400.woff2", "webfonts/fa-solid-900.woff2"]) hash.update(await readFile(resolve(root, "public/pipo-menu", file)));
  assert.equal((await readFile(resolve(root, "public/pipo-menu/.canonical-sha256"), "utf8")).trim(), hash.digest("hex"));
  const runtime = await readFile(resolve(root, "public/pipo-menu/menu.js"), "utf8");
  const helpers = await readFile(resolve(root, "public/pipo-menu/menu-helpers.js"), "utf8");
  const rootView = await readFile(resolve(appRoot, "app/Sources/PipoUI/FoundationView.swift"), "utf8");
  const menuController = await readFile(resolve(appRoot, "app/Sources/PipoApp/PipoMenuBarController.swift"), "utf8");
  for (const action of ["ui.ready", "refresh", "selectTab", "markSeen", "snooze", "openDestination", "copyDetails", "addToCalendar", "setInspectorVisible", "signOut"]) assert.match(runtime, new RegExp(action.replace(".", "\\.")));
  assert.match(runtime, /textContent/);
  assert.match(runtime, /mode === 'demo'/);
  const fixture = JSON.parse(await readFile(resolve(root, "public/pipo-menu/demo-fixture.json"), "utf8"));
  assert.equal(fixture.studentName, "Samwise");
  assert.ok(fixture.courses.length >= 6);
  for (const section of ["nextUp", "schedule", "dueSoon", "newAssignments", "notifications", "messages", "gradeFeedback", "announcements", "resources"]) {
    assert.ok(fixture[section].length, `${section} needs demo content`);
  }
  assert.ok(fixture.courses.every(course => course.id && course.name && course.shortName));
  assert.ok(fixture.localState.pinnedCourseIDs.length && fixture.localState.hiddenCourseIDs.length);
  assert.doesNotMatch(runtime, /innerHTML/);
  assert.match(runtime, /addEventListener\('pipo-state'/);
  assert.match(runtime, /addEventListener\('pipo-response'/);
  assert.match(runtime, /nativeBridge\.request\(action, outbound\)/);
  assert.match(runtime, /requestID: generatedID/);
  assert.match(runtime, /renderState\(state\)/);
  assert.match(runtime, /switchTab\(state\.selectedTab \|\| 'today', false\)/);
  assert.match(runtime, /refreshMinutes/);
  assert.match(runtime, /requestCalendarAccess/);
  assert.doesNotMatch(runtime, /\$\{action\} complete/);
  assert.match(runtime, /source === 'inspector'/);
  assert.match(runtime, /actionButton\.closest\('#inspector-panel'\)/);
  assert.match(runtime, /showToast\(labels\[pending\.?action\]/);
  assert.match(runtime, /toast\.parentElement !== panel/);
  assert.match(runtime, /details unavailable/);
  assert.match(runtime, /fa-chevron-down/);
  for (const action of ["loadCourse", "updateSettings", "updateChannel"]) assert.match(runtime, new RegExp(action));
  assert.match(runtime, /shortName/);
  assert.match(runtime, /short_name/);
  assert.match(runtime, /course_name/);
  assert.match(helpers, /published_grade/);
  assert.match(runtime, /timestamp/);
  assert.doesNotMatch(runtime, /Untitled item|Details unavailable|Course details unavailable/);
  assert.match(html, /id="main-navigation"/);
  assert.match(html, /id="sync-button"[^>]+data-action="refresh"/);
  assert.match(runtime, /mac-card rounded-xl p-2\.5 space-y-1\.5/);
  assert.doesNotMatch(runtime, /Published grade:.*assignments.*grade entries/s);
  assert.match(html, /id="inspector-scroll"/);
  assert.match(html, /id="inspector-nav"/);
  assert.match(html, /aria-controls="inspector-activities-content"/);
  assert.match(html, /aria-controls="inspector-grades-content"/);
  assert.match(html, /html\.embedded body > \.relative[^}]*transform: scale\(1\.27\)/);
  assert.match(html, /@media \(min-width: 736px\)/);
  assert.match(html, /body > \.relative > \.mac-window\.w-\\\[380px\\\] \{[^}]*width: 380px;[^}]*flex: 0 0 380px/);
  assert.match(html, /body > \.relative \{[^}]*gap: 16px/);
  assert.match(html, /width: 340px; height: 580px; max-width: 340px/);
  assert.match(html, /html\[data-host-mode="menuBar"\] \.mac-window\s*\{\s*box-shadow: none/);
  assert.match(html, /--inspector-enter-offset: var\(--pipo-main-width, 380px\)/);
  assert.match(html, /#pipo-header \{[^}]*flex: 0 0 40px;[^}]*height: 40px;[^}]*min-height: 40px;[^}]*max-height: 40px/);
  assert.match(html, /#header-title \{[^}]*left: 50%;[^}]*width: 112px;[^}]*transform: translateX\(-50%\)/);
  assert.match(html, /#sync-button \{[^}]*right: 16px;[^}]*max-width: 112px;[^}]*transform: translateY\(-50%\)/);
  assert.match(html, /#search-section \{[^}]*flex: 0 0 62px;[^}]*height: 62px;[^}]*min-height: 62px;[^}]*max-height: 62px/);
  assert.match(html, /html\[data-host-mode="menuBar"\] #main-panel\.mac-window \{[^}]*backdrop-filter: none/);
  assert.match(html, /html\[data-host-mode="menuBar"\] #inspector-panel\.mac-window \{[^}]*backdrop-filter: blur\(40px\) saturate\(200%\);[^}]*box-shadow:/);
  assert.match(html, /#main-navigation \{[^}]*height: 58px;[^}]*min-height: 58px;[^}]*max-height: 58px/);
  assert.match(html, /#main-navigation \.mac-segmented-btn \{[^}]*height: 34px;[^}]*min-height: 34px;[^}]*max-height: 34px/);
  assert.doesNotMatch(html, /\.mac-segmented-btn \{\s*transition: all/);
  assert.doesNotMatch(html, /id="inspector-panel"[^>]*transition-all/);
  assert.match(runtime, /inspector\.classList\.add\('inspector-exit'\)/);
  assert.match(runtime, /pending\?\.action === 'setInspectorVisible'[\s\S]{0,500}revealInspector/);
  assert.match(runtime, /request\('setInspectorVisible', \{ visible: true[^\n]+\);\s*revealInspector\(openToken\);/);
  assert.match(runtime, /requestAnimationFrame\(\(\) => window\.requestAnimationFrame/);
  assert.match(runtime, /event\.target === inspector && event\.animationName === 'inspector-panel-out'/);
  assert.match(runtime, /inspector\.dataset\.closing !== 'true'/);
  assert.match(html, /@keyframes inspector-panel-in \{[\s\S]*from \{ opacity: 0; transform: translateX\(var\(--inspector-enter-offset, 24px\)\); \}[\s\S]*to \{ opacity: 1; transform: translateX\(0\); \}/);
  assert.match(html, /@keyframes inspector-panel-out \{[\s\S]*from \{ opacity: 1; transform: translateX\(0\); \}[\s\S]*to \{ opacity: 0; transform: translateX\(var\(--inspector-enter-offset, 24px\)\); \}/);
  assert.match(html, /html\[data-host-mode="menuBar"\] body > \.relative > #inspector-viewport \{[^}]*z-index: 10/);
  assert.match(html, /#inspector-viewport\.is-transitioning \{\s*overflow: hidden/);
  assert.match(html, /body > \.relative > #inspector-viewport\.is-active \{\s*pointer-events: auto/);
  assert.match(html, /<div id="inspector-viewport">\s*<div id="inspector-panel"/);
  assert.match(runtime, /viewport\?\.classList\.add\('is-transitioning'\)/);
  assert.match(html, /\.inspector-enter \{\s*animation: inspector-panel-in 220ms cubic-bezier\(0\.16, 1, 0\.3, 1\) both/);
  assert.match(html, /\.inspector-exit \{\s*animation: inspector-panel-out 220ms cubic-bezier\(0\.16, 1, 0\.3, 1\) both/);
  assert.match(rootView, /\.frame\(maxWidth: hostMode == \.menuBar \? \.infinity : nil, alignment: \.trailing\)/);
  assert.match(rootView, /if isSignOutConfirmationPresented \{\s*PipoMenuSignOutConfirmation\(/);
  assert.match(rootView, /private struct PipoMenuSignOutConfirmation: View/);
  assert.match(rootView, /PipoMenuSignOutConfirmation[\s\S]*\.frame\(width: PipoMenuPanelGeometry\.mainSize\.width\)[\s\S]*alignment: \.trailing/);
  assert.doesNotMatch(rootView, /@State private var isInspectorExpanded/);
  assert.doesNotMatch(rootView, /@State private var isMenuInspectorVisible/);
  assert.doesNotMatch(rootView, /PipoMenuGlassBackdrop\([\s\S]{0,100}inspectorVisible:/);
  assert.match(menuController, /applyFrame\(useWideHost: wideHostForSession, animated: false\)/);
  assert.match(menuController, /return wideHostForSession/);
  const statusUpdateBody = menuController.slice(menuController.indexOf("private func updateStatusItem()"), menuController.indexOf("private func applyFrame("));
  assert.doesNotMatch(statusUpdateBody, /repositionVisiblePanel/);
  assert.doesNotMatch(menuController, /alphaValue = 0/);
  assert.match(runtime, /prefers-reduced-motion: reduce/);
  assert.match(runtime, /initializeClickAudio\(\)/);
  assert.match(runtime, /clickAudioPool = \[source, source\.cloneNode\(true\)\]/);
  assert.match(runtime, /addEventListener\('pointerdown',[^\n]+true\)/);
  assert.match(runtime, /event\.key === 'Enter' \|\| event\.key === ' '/);
  assert.match(runtime, /clickAudioPool\.find\(item => item\.paused \|\| item\.ended\)/);
  assert.match(runtime, /previous != null && now - previous < 120/);
  const requestBody = runtime.slice(runtime.indexOf("function request("), runtime.indexOf("function resolveResponse("));
  assert.doesNotMatch(requestBody, /pipo-click|\.play\(/);
  assert.match(runtime, /publishedGrade \|\| 'Grade unavailable'/);
  assert.match(html, /role="tablist"/);
  for (const tab of ["today", "courses", "settings"]) assert.match(html, new RegExp(`id="tab-${tab}"[\\s\\S]{0,100}role="tab"[\\s\\S]{0,100}aria-controls="view-${tab}"`));
  assert.doesNotMatch(html, /h-\[480px\]/);
  assert.match(runtime, /const tabState =/);
  assert.match(runtime, /ArrowRight/);
  assert.match(runtime, /function dismissMenu/);
  assert.match(runtime, /function dismissFilter/);
  assert.match(runtime, /request\('dismissMenu'\)/);
  assert.match(runtime, /setAttribute\('inert'/);
  assert.match(runtime, /timestampISO/);
  assert.match(runtime, /entityKey/);
  assert.match(runtime, /sourceLabel/);
  assert.match(runtime, /Intl\.DateTimeFormat/);
  assert.match(runtime, /detailStatus === 'redacted'/);
  assert.match(runtime, /sectionStatuses/);
  assert.match(runtime, /response\.targetID/);
  assert.match(runtime, /responseRevision >=/);
  assert.match(runtime, /sectionSignatures/);
  assert.match(runtime, /function reconcileCards/);
  assert.match(runtime, /state\.revision <= revision/);
  assert.match(runtime, /\['Up next',[\s\S]*\['Due soon',[\s\S]*\['Schedule',[\s\S]*\['New assignments'/);
});
